# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QVBoxLayout, QWidget)

from pyqtgraph import ImageView

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        if not MainGui.objectName():
            MainGui.setObjectName(u"MainGui")
        MainGui.resize(1300, 671)
        self.centralwidget = QWidget(MainGui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.imageview = ImageView(self.centralwidget)
        self.imageview.setObjectName(u"imageview")
        self.imageview.setGeometry(QRect(550, 10, 600, 600))
        self.snap = QPushButton(self.centralwidget)
        self.snap.setObjectName(u"snap")
        self.snap.setGeometry(QRect(450, 10, 75, 24))
        self.live = QPushButton(self.centralwidget)
        self.live.setObjectName(u"live")
        self.live.setGeometry(QRect(450, 40, 75, 24))
        self.DMD_Calibrate = QPushButton(self.centralwidget)
        self.DMD_Calibrate.setObjectName(u"DMD_Calibrate")
        self.DMD_Calibrate.setGeometry(QRect(290, 590, 91, 24))
        self.stop_movie = QPushButton(self.centralwidget)
        self.stop_movie.setObjectName(u"stop_movie")
        self.stop_movie.setGeometry(QRect(450, 70, 75, 24))
        self.mouse_shoot = QPushButton(self.centralwidget)
        self.mouse_shoot.setObjectName(u"mouse_shoot")
        self.mouse_shoot.setGeometry(QRect(30, 250, 91, 24))
        self.exposureT = QLineEdit(self.centralwidget)
        self.exposureT.setObjectName(u"exposureT")
        self.exposureT.setGeometry(QRect(130, 10, 61, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(18, 10, 81, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 40, 49, 16))
        self.binning = QComboBox(self.centralwidget)
        self.binning.addItem("")
        self.binning.addItem("")
        self.binning.setObjectName(u"binning")
        self.binning.setGeometry(QRect(130, 40, 62, 22))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 90, 91, 31))
        self.nAverage = QLineEdit(self.centralwidget)
        self.nAverage.setObjectName(u"nAverage")
        self.nAverage.setGeometry(QRect(140, 100, 41, 22))
        self.detectCells = QPushButton(self.centralwidget)
        self.detectCells.setObjectName(u"detectCells")
        self.detectCells.setGeometry(QRect(30, 180, 151, 24))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 130, 81, 16))
        self.minsize = QLineEdit(self.centralwidget)
        self.minsize.setObjectName(u"minsize")
        self.minsize.setGeometry(QRect(30, 150, 31, 22))
        self.maxsize = QLineEdit(self.centralwidget)
        self.maxsize.setObjectName(u"maxsize")
        self.maxsize.setGeometry(QRect(70, 150, 31, 22))
        self.somasStims = QPushButton(self.centralwidget)
        self.somasStims.setObjectName(u"somasStims")
        self.somasStims.setGeometry(QRect(30, 290, 111, 24))
        self.ManualGroup = QPushButton(self.centralwidget)
        self.ManualGroup.setObjectName(u"ManualGroup")
        self.ManualGroup.setGeometry(QRect(30, 330, 101, 24))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(120, 130, 111, 16))
        self.cellpose_diameter = QLineEdit(self.centralwidget)
        self.cellpose_diameter.setObjectName(u"cellpose_diameter")
        self.cellpose_diameter.setGeometry(QRect(140, 150, 41, 22))
        self.RandGroup = QPushButton(self.centralwidget)
        self.RandGroup.setObjectName(u"RandGroup")
        self.RandGroup.setGeometry(QRect(30, 370, 111, 24))
        self.group_size = QLineEdit(self.centralwidget)
        self.group_size.setObjectName(u"group_size")
        self.group_size.setGeometry(QRect(150, 370, 31, 22))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 350, 61, 16))
        self.createProtocol = QPushButton(self.centralwidget)
        self.createProtocol.setObjectName(u"createProtocol")
        self.createProtocol.setGeometry(QRect(230, 230, 111, 24))
        self.loadProtocol = QPushButton(self.centralwidget)
        self.loadProtocol.setObjectName(u"loadProtocol")
        self.loadProtocol.setGeometry(QRect(230, 260, 111, 24))
        self.runProtocol = QPushButton(self.centralwidget)
        self.runProtocol.setObjectName(u"runProtocol")
        self.runProtocol.setGeometry(QRect(230, 290, 111, 24))
        self.loadTest = QPushButton(self.centralwidget)
        self.loadTest.setObjectName(u"loadTest")
        self.loadTest.setGeometry(QRect(230, 390, 111, 24))
        self.stopProtocol = QPushButton(self.centralwidget)
        self.stopProtocol.setObjectName(u"stopProtocol")
        self.stopProtocol.setGeometry(QRect(230, 320, 111, 24))
        self.testGroup = QPushButton(self.centralwidget)
        self.testGroup.setObjectName(u"testGroup")
        self.testGroup.setGeometry(QRect(230, 360, 111, 24))
        self.light_click_pixels_size = QLineEdit(self.centralwidget)
        self.light_click_pixels_size.setObjectName(u"light_click_pixels_size")
        self.light_click_pixels_size.setGeometry(QRect(150, 250, 41, 22))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 230, 81, 16))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 440, 251, 171))
        self.widget = QWidget(self.groupBox)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 20, 218, 150))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.update_stage = QPushButton(self.widget)
        self.update_stage.setObjectName(u"update_stage")

        self.verticalLayout.addWidget(self.update_stage)

        self.stage_position = QLabel(self.widget)
        self.stage_position.setObjectName(u"stage_position")
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.stage_position.setFont(font)
        self.stage_position.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.stage_position)

        self.zero_stage = QPushButton(self.widget)
        self.zero_stage.setObjectName(u"zero_stage")

        self.verticalLayout.addWidget(self.zero_stage)

        self.move_stage = QPushButton(self.widget)
        self.move_stage.setObjectName(u"move_stage")

        self.verticalLayout.addWidget(self.move_stage)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")

        self.horizontalLayout.addWidget(self.label_8)

        self.xpos = QLineEdit(self.widget)
        self.xpos.setObjectName(u"xpos")

        self.horizontalLayout.addWidget(self.xpos)

        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")

        self.horizontalLayout.addWidget(self.label_9)

        self.ypos = QLineEdit(self.widget)
        self.ypos.setObjectName(u"ypos")

        self.horizontalLayout.addWidget(self.ypos)


        self.verticalLayout.addLayout(self.horizontalLayout)

        MainGui.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainGui)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1300, 21))
        self.menuTab = QMenu(self.menubar)
        self.menuTab.setObjectName(u"menuTab")
        self.menuTab2 = QMenu(self.menubar)
        self.menuTab2.setObjectName(u"menuTab2")
        MainGui.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainGui)
        self.statusbar.setObjectName(u"statusbar")
        MainGui.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuTab.menuAction())
        self.menubar.addAction(self.menuTab2.menuAction())

        self.retranslateUi(MainGui)

        QMetaObject.connectSlotsByName(MainGui)
    # setupUi

    def retranslateUi(self, MainGui):
        MainGui.setWindowTitle(QCoreApplication.translate("MainGui", u"MainGui", None))
        self.snap.setText(QCoreApplication.translate("MainGui", u"Snap", None))
        self.live.setText(QCoreApplication.translate("MainGui", u"Live", None))
#if QT_CONFIG(whatsthis)
        self.DMD_Calibrate.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Perform calibration between camera image and DMD.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.DMD_Calibrate.setText(QCoreApplication.translate("MainGui", u"Calibrate DMD", None))
        self.stop_movie.setText(QCoreApplication.translate("MainGui", u"Stop Movie", None))
        self.mouse_shoot.setText(QCoreApplication.translate("MainGui", u"Click and light", None))
        self.exposureT.setText(QCoreApplication.translate("MainGui", u"2", None))
        self.label.setText(QCoreApplication.translate("MainGui", u"Exposure (ms)", None))
        self.label_2.setText(QCoreApplication.translate("MainGui", u"Binning", None))
        self.binning.setItemText(0, QCoreApplication.translate("MainGui", u"1x1", None))
        self.binning.setItemText(1, QCoreApplication.translate("MainGui", u"2x2", None))

        self.label_3.setText(QCoreApplication.translate("MainGui", u"Soma n images \n"
" to average ", None))
#if QT_CONFIG(tooltip)
        self.nAverage.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.nAverage.setText(QCoreApplication.translate("MainGui", u"16", None))
#if QT_CONFIG(whatsthis)
        self.detectCells.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Using CellPose to detect neuronal somas automatically. </p><p>CellPose Diameter set the minimal size of soma.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.detectCells.setText(QCoreApplication.translate("MainGui", u"Detect cells", None))
        self.label_4.setText(QCoreApplication.translate("MainGui", u"MinMax size", None))
        self.minsize.setText(QCoreApplication.translate("MainGui", u"20", None))
        self.maxsize.setText(QCoreApplication.translate("MainGui", u"70", None))
#if QT_CONFIG(whatsthis)
        self.somasStims.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Run SLM stimulation to all detected somas in the DMD_dir</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.somasStims.setText(QCoreApplication.translate("MainGui", u"Stimulate all cells", None))
#if QT_CONFIG(tooltip)
        self.ManualGroup.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.ManualGroup.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Manually grouping detected cells by mouse click</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.ManualGroup.setText(QCoreApplication.translate("MainGui", u"Click and group", None))
        self.label_5.setText(QCoreApplication.translate("MainGui", u"CellPose Diameter", None))
        self.cellpose_diameter.setText(QCoreApplication.translate("MainGui", u"13", None))
        self.RandGroup.setText(QCoreApplication.translate("MainGui", u"Random grouping", None))
        self.group_size.setText(QCoreApplication.translate("MainGui", u"3", None))
        self.label_6.setText(QCoreApplication.translate("MainGui", u"Group size", None))
        self.createProtocol.setText(QCoreApplication.translate("MainGui", u"Create Protocol", None))
        self.loadProtocol.setText(QCoreApplication.translate("MainGui", u"Load Protocol", None))
        self.runProtocol.setText(QCoreApplication.translate("MainGui", u"Run Protocol", None))
        self.loadTest.setText(QCoreApplication.translate("MainGui", u"Load test culture", None))
        self.stopProtocol.setText(QCoreApplication.translate("MainGui", u"Stop protocol", None))
#if QT_CONFIG(tooltip)
        self.testGroup.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.testGroup.setText(QCoreApplication.translate("MainGui", u"Set Test group", None))
        self.light_click_pixels_size.setText(QCoreApplication.translate("MainGui", u"10", None))
        self.label_7.setText(QCoreApplication.translate("MainGui", u"Light pixel size", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainGui", u"Stage", None))
#if QT_CONFIG(tooltip)
        self.update_stage.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.update_stage.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Run SLM stimulation to all detected somas in the DMD_dir</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.update_stage.setText(QCoreApplication.translate("MainGui", u"Update stage position", None))
        self.stage_position.setText(QCoreApplication.translate("MainGui", u"0,0", None))
#if QT_CONFIG(whatsthis)
        self.zero_stage.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Manually grouping detected cells by mouse click</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.zero_stage.setText(QCoreApplication.translate("MainGui", u"Zero stage pos.", None))
#if QT_CONFIG(tooltip)
        self.move_stage.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.move_stage.setWhatsThis(QCoreApplication.translate("MainGui", u"<html><head/><body><p>Run SLM stimulation to all detected somas in the DMD_dir</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.move_stage.setText(QCoreApplication.translate("MainGui", u"Move to coordinates", None))
        self.label_8.setText(QCoreApplication.translate("MainGui", u"X", None))
        self.xpos.setText(QCoreApplication.translate("MainGui", u"10", None))
        self.label_9.setText(QCoreApplication.translate("MainGui", u"Y", None))
        self.ypos.setText(QCoreApplication.translate("MainGui", u"10", None))
        self.menuTab.setTitle(QCoreApplication.translate("MainGui", u"Tab", None))
        self.menuTab2.setTitle(QCoreApplication.translate("MainGui", u"Tab2", None))
    # retranslateUi

